### ISSUE TITLE
Add examples of output

### ISSUE THREAD

**Issue by hugolpz** [iwasingh/Wikicompiler#2]
I looked into [/tests/data](https://github.com/iwasingh/Wikicompiler/tree/master/tests/data), [examples](https://github.com/iwasingh/Wikicompiler/tree/master/examples) and [/docs](https://github.com/iwasingh/Wikicompiler/tree/master/docs), I barely found an example of output. After some digging, I found this good example 👍🏼 :
![Screenshot_2021-03-27_17-59-39](https://user-images.githubusercontent.com/1420189/112728195-69b60d80-8f26-11eb-84a4-ba14e16341d6.png)

Could be interesting to add examples of outputs .txt files in /docs, to then cite them in the readme.md. You could pair those `output` files with the `example` links you already have, and who point to code sample, so we see something like _([code sample]() | [output sample]())_ or _(example: [input]() | [code]() | [output]())_. At minima, the image above is itself very interesting for people discovering your project and could be integrated to the README.md.

**Comment by iwasingh** [comment]
@hugolpz Thank you for the feedback, i'll put some output examples and update the README accordingly

**Comment by hugolpz** [comment]
Side note: I cited your project in https://github.com/google/corpuscrawler/issues/78 , a linguistic diversity project who kick started Google Android keyboard input suggestions (if i understood well), and whom's data (UNILEX) now helps wiktionaries for words to document. The corpuscrawler projects is lowly active thanks to few volunteers, but initially generated data for ~1000 languages. They both could gain from clean corpus extrated from Wikipedia's 300+ languages.

**Comment by iwasingh** [comment]
@hugolpz Added some examples https://github.com/iwasingh/Wikicompiler#examples.
Thank your for the citation
I would like to let you know that this project was born inside a  search engine project https://github.com/iwasingh/Wikoogle i made a while ago. I needed a clean corpus to do some information retrieval tasks similar to corpuscrawler and at the time i was able to find only two ways to get a clean text:
 * Use wikipedia api:  https://www.mediawiki.org/wiki/API:Get_the_contents_of_a_page or similar which was not suitable for me(not batch processing, parsing wikitext is easier than the html of a wikipedia page)
 * https://github.com/attardi/wikiextractor which might do the job but is not that extensible and is doing too much for what i needed(i didn't need template resolution or other complex tag resolutions) and that's why i decided to make a new one

**Comment by hugolpz** [comment]
API calls and Wikiextrator are the two ways i found so far. WCC is a new avenue. Similarly, i am not convinced that templates would had value to a linguistic project. Most templates are infoboxes (data) or community warnings. Minority are inline templates, by example to help convert US miles into SI km. But then again, it isnt of high value for high frequency lexical linguistic.

Also, do you have a built in way to ignore the `== See also ==` and `== References ==` sections ? Or is there a recommended way to remove such content ? Ortherwise i think some brutal regex will do.

Thank you for the project history & review. 🙏🏼

**Comment by iwasingh** [comment]
Well, there are several way to ignore those headers,
the simplest one that came up in my mind is to add these 2 headers inside the `IGNORED_TAGS`  of symbols in the lexer  module https://github.com/iwasingh/Wikicompiler/blob/master/lexer/symbols.py#L219

`r'== See also =='`
`r'== References =='`

**Comment by iwasingh** [comment]
I'm gonna close the issue, feel free to open another one for other questions or discussions

**Comment by hugolpz** [comment]
Yes, thank for the readme fix 👍🏼
